Rejects commits without ticket number in non-feature branches

diff --git a/hooks/prepare-commit-msg b/hooks/prepare-commit-msg
--- a/hooks/prepare-commit-msg
+++ b/hooks/prepare-commit-msg
@@ -7,14 +7,26 @@
 
 jira_project_key="FOO|BAR|BAZ" # specify JIRA project keys here
 
+commitMessage=$(cat $1) # $1 means input parameter - which is file with the commit message
 branch="$(git rev-parse --abbrev-ref HEAD)" # current branch name
+
 if [ -n ${branch} ] ; then # branch name is not an empty string
   issueName=`echo $branch | grep -Eo "(${jira_project_key})-[[:digit:]]+"` # project keys of your JIRA projects, parsed from GIT branch name;
-  if [ -n ${issueName} ] ; then # an issue name has been parsed
+  if [ -n "${issueName}" ] && [[ "${issueName}" != " " ]] ; then # an issue name has been parsed
   	# see "project key" at https://confluence.atlassian.com/display/JIRA/Defining+a+Project#DefiningaProject-Creatingaproject
-    commitMessage=$(cat $1) # $1 means input parameter - which is file with the commit message
     if [ -n "${commitMessage}" ] && [[ "${commitMessage}" != "$issueName"* ]] ; then  # original commit message does not start with issue name yet
       echo "$issueName $commitMessage" > $1 # rewriting original commit message with prefixed one
     fi
+  else
+  	# If we are not in a feature branch, fetch the issue from the commit message
+  	issueName=`echo $commitMessage | grep -Eo "(${jira_project_key})-[[:digit:]]+"`
+  	if [ -n "${issueName}" ] && [[ "${issueName}" != " " ]] ; then
+  		if [ -n "${commitMessage}" ] && [[ "${commitMessage}" != "$issueName"* ]] ; then  # original commit message does not start with issue name yet
+      		echo "$issueName $commitMessage" > $1 # rewriting original commit message with prefixed one
+    	fi
+  	else
+  		echo >&2 "! ERROR: Commit message is missing or have an incorrent JIRA issue number, commit rejected!"
+		exit 1
+	fi
   fi
 fi
